import { Calculator } from '../types';

export const V14_BUSINESS_CALCULATORS: Calculator[] = [
  {
    id: 'gross-revenue',
    name: 'Gross Revenue Calculator',
    slug: 'gross-revenue-calculator',
    category: 'business',
    description: 'Calculate the total top-line gross revenue generated by your business based on sales volumes and unit prices.',
    seoTitle: 'Gross Revenue & Business Top-Line Income Calculator',
    seoDescription: 'Input sold units and unit price targets across multiple lines to find your total overall gross revenue.',
    inputs: [
      { id: 'unitsA', label: 'Product A Units Sold', type: 'number', defaultValue: 1200 },
      { id: 'priceA', label: 'Product A Unit Price ($)', type: 'number', defaultValue: 45 },
      { id: 'unitsB', label: 'Product B Units Sold', type: 'number', defaultValue: 600 },
      { id: 'priceB', label: 'Product B Unit Price ($)', type: 'number', defaultValue: 120 },
      { id: 'serviceHours', label: 'Billable Service Hours Worked', type: 'number', defaultValue: 150 },
      { id: 'hourlyRate', label: 'Hourly Service Fees ($)', type: 'number', defaultValue: 85 }
    ],
    formula: 'Gross Revenue = sum(Units_i * Price_i) + (Service Hours * Hourly Rate)',
    explanation: 'Gross revenue represents the overall top-line earnings entry of a business ledger before deducting refund items, production costs, taxes, or operating overheads.',
    example: 'Selling 1,200 units at $45 ($54,000) and 600 units at $120 ($72,000), plus billing 150 hours at $85 ($12,750), yields $138,750 in gross returns.',
    faq: [
      { question: 'What is the utility of Gross Revenue?', answer: 'It represents consumer demand or sales capacity. It is the initial starting variable from which all standard corporate profitability studies derive.' },
      { question: 'Does gross revenue include tax liabilities?', answer: 'Generally yes, unless sales taxes are kept separate from standard retail ledger values.' }
    ],
    relatedSlugs: ['net-revenue-calculator', 'product-margin-calculator'],
    calculate: (inputs) => {
      const uA = Number(inputs.unitsA || 0);
      const pA = Number(inputs.priceA || 0);
      const uB = Number(inputs.unitsB || 0);
      const pB = Number(inputs.priceB || 0);
      const sh = Number(inputs.serviceHours || 0);
      const hr = Number(inputs.hourlyRate || 0);

      const revA = uA * pA;
      const revB = uB * pB;
      const revServ = sh * hr;
      const total = revA + revB + revServ;

      return {
        results: [
          { label: 'Total Gross Revenue', value: `$${total.toFixed(2)}`, isPrimary: true },
          { label: 'Product A Revenue', value: `$${revA.toFixed(2)}` },
          { label: 'Product B Revenue', value: `$${revB.toFixed(2)}` },
          { label: 'Service Income', value: `$${revServ.toFixed(2)}` }
        ],
        chartData: [
          { name: 'Product A', value: revA },
          { name: 'Product B', value: revB },
          { name: 'Service Billing', value: revServ }
        ]
      };
    }
  },
  {
    id: 'net-revenue',
    name: 'Net Revenue Calculator',
    slug: 'net-revenue-calculator',
    category: 'business',
    description: 'Calculate net corporate revenue by subtracting refunds, client discounts, and transaction allowances from top-line gross calculations.',
    seoTitle: 'Net Revenue & Retail Returns Calculator',
    seoDescription: 'Define true business turnover margins. Subtract invoice discounts and returns from gross revenue.',
    inputs: [
      { id: 'grossRevenue', label: 'Gross Revenue ($)', type: 'number', defaultValue: 150000 },
      { id: 'refunds', label: 'Refunds & Returns ($)', type: 'number', defaultValue: 6500 },
      { id: 'discounts', label: 'Discounts & Promotional Credits ($)', type: 'number', defaultValue: 3200 },
      { id: 'transactionFees', label: 'Merchant Billing & Card Fees ($)', type: 'number', defaultValue: 4100 }
    ],
    formula: 'Net Revenue = Gross Revenue - Refunds - Discounts - Transaction Fees',
    explanation: 'Net revenue represents actual monies successfully retained by a business entity after administrative transaction frictions are fully parsed, but prior to core cost of goods sold (COGS) calculations.',
    example: 'A business generating $150,000 gross revenue with $6,500 refunds, $3,200 discounts, and $4,100 card processing fees retains $136,200 in net revenue.',
    faq: [
      { question: 'Why does Net Revenue differ from Net Income?', answer: 'Net revenue represents sales after immediate checkout-related deductions. Net income is what remains after subtracting ALL operating expenses, salaries, COGS, interest, and federal taxes.' },
      { question: 'Is processing fee subtraction standard for net revenue?', answer: 'Different accountants have different standard treatments, but incorporating merchant frictions ensures realistic liquidity assessments.' }
    ],
    relatedSlugs: ['gross-revenue-calculator', 'business-expense-ratio-calculator'],
    calculate: (inputs) => {
      const gross = Number(inputs.grossRevenue || 0);
      const ref = Number(inputs.refunds || 0);
      const disc = Number(inputs.discounts || 0);
      const fees = Number(inputs.transactionFees || 0);

      const net = Math.max(0, gross - ref - disc - fees);
      const deductionRatio = gross > 0 ? ((ref + disc + fees) / gross) * 100 : 0;

      return {
        results: [
          { label: 'Total Net Revenue', value: `$${net.toFixed(2)}`, isPrimary: true },
          { label: 'Checkout Deductions', value: `$${(ref + disc + fees).toFixed(2)}` },
          { label: 'Retained Yield Rate', value: `${(100 - deductionRatio).toFixed(1)}%` },
          { label: 'Lost Margin Ratio', value: `${deductionRatio.toFixed(1)}%` }
        ],
        chartData: [
          { name: 'Retained Sales Net', value: Math.round(net) },
          { name: 'Allowances & Fees', value: Math.round(ref + disc + fees) }
        ]
      };
    }
  },
  {
    id: 'business-expense-ratio',
    name: 'Business Expense Ratio Calculator',
    slug: 'business-expense-ratio-calculator',
    category: 'business',
    description: 'Assess corporate operational leverage by finding the percentage of business revenue consumed by operating expenditures.',
    seoTitle: 'Business Operating Expense Ratio (OER) Solver',
    seoDescription: 'Obtain critical corporate efficiency ratios. Input operating expenditures and revenues to generate immediate compliance reports.',
    inputs: [
      { id: 'revenue', label: 'Net Annual Revenue ($)', type: 'number', defaultValue: 300000 },
      { id: 'salaries', label: 'Employee Salaries & Payroll ($)', type: 'number', defaultValue: 110000 },
      { id: 'marketing', label: 'Ad Spends & Marketing ($)', type: 'number', defaultValue: 45000 },
      { id: 'rentUtilities', label: 'Office Rent & Facilities ($)', type: 'number', defaultValue: 35000 },
      { id: 'softwareInventory', label: 'Software Licenses & Material Inventory ($)', type: 'number', defaultValue: 25000 }
    ],
    formula: 'Operating Expense Ratio = (Total Operating Expenses / Net Revenue) * 100',
    explanation: 'A lower operating expense ratio indicates a highly efficient corporate structure, enabling significant profit margins and capital reserve generation.',
    example: 'An annual net revenue of $300,000 compared against $215,000 in total operating costs yields an operating expense ratio of 71.67%.',
    faq: [
      { question: 'What is a healthy corporate expense ratio?', answer: 'Healthy ratios vary by sector. Software companies can operate at 60-70%, whereas retail operations with massive physical supply chains have tighter operating targets.' },
      { question: 'Are capital expenditures included in OER?', answer: 'No. Capital expenditures (CapEx), such as buying land or heavy machinery, are amortized over years and are excluded from day-to-day operating reports.' }
    ],
    relatedSlugs: ['gross-revenue-calculator', 'profit-forecast-calculator'],
    calculate: (inputs) => {
      const rev = Number(inputs.revenue || 1);
      const sal = Number(inputs.salaries || 0);
      const mkt = Number(inputs.marketing || 0);
      const rent = Number(inputs.rentUtilities || 0);
      const soft = Number(inputs.softwareInventory || 0);

      const totalOps = sal + mkt + rent + soft;
      const ratio = (totalOps / rev) * 100;
      const margin = Math.max(0, 100 - ratio);

      return {
        results: [
          { label: 'Operating Expense Ratio', value: `${ratio.toFixed(2)}%`, isPrimary: true },
          { label: 'Total Operating Expenses', value: `$${totalOps.toFixed(2)}` },
          { label: 'Net Cash Reserve Surplus', value: `$${(rev - totalOps).toFixed(2)}` },
          { label: 'Remaining Profit Margin', value: `${margin.toFixed(2)}%` }
        ],
        chartData: [
          { name: 'Employee Payroll', value: sal },
          { name: 'Ad & Marketing', value: mkt },
          { name: 'Rent & Logistics', value: rent },
          { name: 'Softwares & Materials', value: soft },
          { name: 'Retained Cash Reserves', value: Math.max(0, rev - totalOps) }
        ]
      };
    }
  },
  {
    id: 'profit-forecast',
    name: 'Profit Forecast Calculator',
    slug: 'profit-forecast-calculator',
    category: 'business',
    description: 'Forecast forward net business profits based on estimated organic monthly sales growth and operating overhead targets.',
    seoTitle: 'Future Profit & Sales Forecast Calculator',
    seoDescription: 'Project company performance horizons. Model forward cash reserves incorporating growth and expense escalation triggers.',
    inputs: [
      { id: 'startingMonthly', label: 'Starting Monthly Revenue ($)', type: 'number', defaultValue: 20000 },
      { id: 'growthRate', label: 'Estimated Monthly Sales Growth (%)', type: 'number', defaultValue: 3 },
      { id: 'cogsPercentage', label: 'Cost of Goods Sold (COGS) Ratio (%)', type: 'number', defaultValue: 35 },
      { id: 'fixedMonthlyRent', label: 'Fixed Monthly Overhead Burden ($)', type: 'number', defaultValue: 8000 },
      { id: 'forecastSpan', label: 'Forward Projections Range (Months)', type: 'number', defaultValue: 12 }
    ],
    formula: 'Monthly Net = (Revenue_i * (1 - COGS/100)) - Fixed Overhead\nAccumulated Profit is the cumulative sum over the specified months.',
    explanation: 'Evaluating cash flow trajectories with variable factors allows business leads to accurately plan hires, logistics, and capital expansions.',
    example: 'Starting with $20,000 monthly sales at a 3% growth rate, 35% COGS, and $8k monthly overhead yields a cumulative net profit of $66,692.65 over a year.',
    faq: [
      { question: 'What does COGS incorporate?', answer: 'Cost of Goods Sold includes direct labor and materials required to manufacture a physical product or deliver a digital service.' },
      { question: 'Why is fixed overhead constant?', answer: 'Fixed overhead represents baseline survival costs, such as office rent and SaaS subscriptions, which do not change alongside sales volumes.' }
    ],
    relatedSlugs: ['business-expense-ratio-calculator', 'sales-target-calculator'],
    calculate: (inputs) => {
      const start = Number(inputs.startingMonthly || 20000);
      const gr = Number(inputs.growthRate || 3) / 100;
      const cogsRatio = Number(inputs.cogsPercentage || 35) / 100;
      const fixed = Number(inputs.fixedMonthlyRent || 8000);
      const span = Number(inputs.forecastSpan || 12);

      let totalGrossRev = 0;
      let totalNetProf = 0;
      let activeRev = start;

      for (let i = 0; i < span; i++) {
        const cogsCost = activeRev * cogsRatio;
        const netProf = (activeRev - cogsCost) - fixed;

        totalGrossRev += activeRev;
        totalNetProf += netProf;

        activeRev *= (1 + gr);
      }

      return {
        results: [
          { label: 'Cumulative Net Profit Forecast', value: `$${totalNetProf.toFixed(2)}`, isPrimary: true },
          { label: 'Total Accumulated Revenue', value: `$${totalGrossRev.toFixed(2)}` },
          { label: 'Final Month End Revenue', value: `$${(activeRev / (1+gr)).toFixed(2)}` },
          { label: 'Blended Cost Burden Ratio', value: `${(((totalGrossRev - totalNetProf) / totalGrossRev) * 100).toFixed(1)}%` }
        ],
        chartData: [
          { name: 'Projected Net Profit', value: Math.max(0, Math.round(totalNetProf)) },
          { name: 'Manufacturing & COGS Costs', value: Math.round(totalGrossRev * cogsRatio) },
          { name: 'Baseline Fixed Overhead', value: Math.round(fixed * span) }
        ]
      };
    }
  },
  {
    id: 'sales-target',
    name: 'Sales Target Calculator',
    slug: 'sales-target-calculator',
    category: 'business',
    description: 'Calculate the volume of retail unit sales needed to achieve your target net profit objectives.',
    seoTitle: 'Target Sales Volume & Breakeven Calculator',
    seoDescription: 'Input target profits and overhead elements to instantly establish custom sales goals.',
    inputs: [
      { id: 'targetProfit', label: 'Desired Monthly Net Profit ($)', type: 'number', defaultValue: 10000 },
      { id: 'fixedCosts', label: 'Monthly Baseline Fixed Costs ($)', type: 'number', defaultValue: 6500 },
      { id: 'pricePerUnit', label: 'Selling Unit Price ($)', type: 'number', defaultValue: 150 },
      { id: 'costPerUnit', label: 'Variable Cost of Unit ($)', type: 'number', defaultValue: 60 }
    ],
    formula: 'Target Units = (Fixed Costs + Target Profit) / (Price - Cost)',
    explanation: 'Quantifies concrete, achievable sales unit goals for sales teams based on pricing structures and fixed business overheads.',
    example: 'To achieve a $10,000 profit alongside $6,500 fixed costs on products sold at $150 with $60 COGS, you need to sell exactly 184 units.',
    faq: [
      { question: 'What represents unit contribution margin?', answer: 'The contribution margin represents excess cash per sale of a unit. Calculated using [Price - Variable Cost], this cash goes toward paying down fixed overheads.' },
      { question: 'What is the absolute breakeven target?', answer: 'Set the Desired Net Profit to $0. This calculates the precise sales volume required to cover your fixed costs.' }
    ],
    relatedSlugs: ['product-margin-calculator', 'profit-forecast-calculator'],
    calculate: (inputs) => {
      const profit = Number(inputs.targetProfit || 10000);
      const fixed = Number(inputs.fixedCosts || 6500);
      const price = Number(inputs.pricePerUnit || 150);
      const cost = Number(inputs.costPerUnit || 60);

      const contributionMargin = price - cost;
      let unitsNeeded = 0;
      if (contributionMargin > 0) {
        unitsNeeded = Math.ceil((fixed + profit) / contributionMargin);
      }

      const grossSalesVal = unitsNeeded * price;
      const totalCOGS = unitsNeeded * cost;

      return {
        results: [
          { label: 'Required Sales Units Target', value: `${unitsNeeded} Units`, isPrimary: true },
          { label: 'Target Gross Sales Value', value: `$${grossSalesVal.toFixed(2)}` },
          { label: 'Total Variable Unit COGS', value: `$${totalCOGS.toFixed(2)}` },
          { label: 'Marginal Profit per Unit', value: `$${contributionMargin.toFixed(2)}` }
        ],
        chartData: [
          { name: 'Target Net Profit', value: profit },
          { name: 'Fixed Overhead Cost', value: fixed },
          { name: 'Variable Product Costs', value: totalCOGS }
        ]
      };
    }
  },
  {
    id: 'sales-commission',
    name: 'Sales Commission Calculator',
    slug: 'sales-commission-calculator',
    category: 'business',
    description: 'Calculate total payouts for sales professionals based on tiered commission rates and quarterly sales volume milestones.',
    seoTitle: 'Tiered Sales Commission & Base Payout Calculator',
    seoDescription: 'Evaluate commissions for your sales team. Configure tiered percentage milestones and base pay scales easily.',
    inputs: [
      { id: 'salesVolume', label: 'Total Sales Volume Achieved ($)', type: 'number', defaultValue: 75000 },
      { id: 'basePay', label: 'Base Monthly Salary ($)', type: 'number', defaultValue: 3000 },
      { id: 'tier1Limit', label: 'Tier 1 Max Limit ($)', type: 'number', defaultValue: 30000 },
      { id: 'rate1', label: 'Tier 1 Commission Rate (%)', type: 'number', defaultValue: 5 },
      { id: 'rate2', label: 'Tier 2 Commission Rate (%)', type: 'number', defaultValue: 8 }
    ],
    formula: 'Commission is calculated tiered: Tier 1 Rate up to limit, Tier 2 Rate on the excess.',
    explanation: 'Allows sales managers to model tiered incentive plans that motivate high performers and align with business objectives.',
    example: 'Generating $75,000 in sales with $3k base pay yields a $5,100 commission ($1,500 from Tier 1 + $3,600 from Tier 2), resulting in an $8,100 payout.',
    faq: [
      { question: 'What is tiered commissioning?', answer: 'An incentive structure where the commission percentage increases as the sales associate crosses specific volume milestones.' },
      { question: 'Is commission paid on gross or net sales?', answer: 'Most standard contracts pay commissions on invoice sales values after returns are accounted for.' }
    ],
    relatedSlugs: ['sales-target-calculator', 'employee-productivity-calculator'],
    calculate: (inputs) => {
      const vol = Number(inputs.salesVolume || 75000);
      const base = Number(inputs.basePay || 3000);
      const t1Limit = Number(inputs.tier1Limit || 30000);
      const r1 = Number(inputs.rate1 || 5) / 100;
      const r2 = Number(inputs.rate2 || 8) / 100;

      let comm = 0;
      let t1Sales = 0;
      let t2Sales = 0;

      if (vol <= t1Limit) {
        t1Sales = vol;
        comm = vol * r1;
      } else {
        t1Sales = t1Limit;
        t2Sales = vol - t1Limit;
        comm = (t1Limit * r1) + (t2Sales * r2);
      }

      const totalPayout = base + comm;

      return {
        results: [
          { label: 'Total Monthly Payroll Payout', value: `$${totalPayout.toFixed(2)}`, isPrimary: true },
          { label: 'Commission Earned', value: `$${comm.toFixed(2)}` },
          { label: 'Base Salary Guaranteed', value: `$${base.toFixed(2)}` },
          { label: 'Tier 1 Commission Share', value: `$${(t1Sales * r1).toFixed(2)}` },
          { label: 'Tier 2 Commission Share', value: `$${(t2Sales * r2).toFixed(2)}` }
        ],
        chartData: [
          { name: 'Guaranteed Base Pay', value: base },
          { name: 'Commissions Earned', value: comm }
        ]
      };
    }
  },
  {
    id: 'employee-productivity',
    name: 'Employee Productivity Calculator',
    slug: 'employee-productivity-calculator',
    category: 'business',
    description: 'Calculate productivity indices based on actual revenue outputs versus staff headcount and payroll allocations.',
    seoTitle: 'Employee Productivity & Output Ratio Calculator',
    seoDescription: 'Track team performance metrics. Compare total unit outputs or revenues against active staff working hours.',
    inputs: [
      { id: 'revenueGenerated', label: 'Company Monthly Revenue ($)', type: 'number', defaultValue: 120000 },
      { id: 'headcount', label: 'Active Team Headcount', type: 'number', defaultValue: 6 },
      { id: 'hoursWorked', label: 'Total Staff Work Hours (Combined)', type: 'number', defaultValue: 960 },
      { id: 'laborCost', label: 'Total Combined Payroll Cost ($)', type: 'number', defaultValue: 45000 }
    ],
    formula: 'Productivity = Revenue / Total Staff Work Hours\nLabor ROI = Revenue / Payroll Cost',
    explanation: 'Track organizational health. Evaluate if team growth matches scaling metrics directly.',
    example: 'An office generating $120,000 monthly with 6 staff working 960 hours produces $125 of revenue per hour worked, yielding a 2.67x labor ROI.',
    faq: [
      { question: 'What is a typical labor ROI?', answer: 'For standard service operations, targeting a Labor ROI multiplier above 2.5x - 3.0x is critical to maintain net profitability.' },
      { question: 'How is combined staff hours calculated?', answer: 'Headcount multiplied by average hours worked per month per person (typically 160 hours per full-time associate).' }
    ],
    relatedSlugs: ['business-efficiency-calculator', 'sales-commission-calculator'],
    calculate: (inputs) => {
      const rev = Number(inputs.revenueGenerated || 120000);
      const count = Number(inputs.headcount || 6);
      const hours = Number(inputs.hoursWorked || 960);
      const labor = Number(inputs.laborCost || 45000);

      const revPerHour = hours > 0 ? rev / hours : 0;
      const revPerHead = count > 0 ? rev / count : 0;
      const laborROI = labor > 0 ? rev / labor : 0;

      return {
        results: [
          { label: 'Revenue per Staff Hour', value: `$${revPerHour.toFixed(2)}`, isPrimary: true },
          { label: 'Revenue per Employee', value: `$${revPerHead.toFixed(2)}` },
          { label: 'Labor Payroll ROI Multiplier', value: `${laborROI.toFixed(2)}x` },
          { label: 'Labor Percentage of Revenue', value: `${((labor / rev) * 100).toFixed(1)}%` }
        ],
        chartData: [
          { name: 'Revenue Yield', value: Math.round(rev) },
          { name: 'Payroll Costs Combined', value: Math.round(labor) }
        ]
      };
    }
  },
  {
    id: 'business-efficiency',
    name: 'Business Efficiency Calculator',
    slug: 'business-efficiency-calculator',
    category: 'business',
    description: 'Calculate critical operational metrics including Inventory Turnover, Days Sales Outstanding (DSO), and Return on Assets.',
    seoTitle: 'Core Business Efficiency & DSO Metrics Solver',
    seoDescription: 'Obtain critical inventory turnovers and average checkout collection days to assess logistics and collections efficiency.',
    inputs: [
      { id: 'salesRevenue', label: 'Annual Sales Revenue ($)', type: 'number', defaultValue: 500000 },
      { id: 'cogs', label: 'Cost of Goods Sold (COGS) ($)', type: 'number', defaultValue: 280000 },
      { id: 'averageInventory', label: 'Average Inventory Held ($)', type: 'number', defaultValue: 40000 },
      { id: 'receivables', label: 'Average Accounts Receivable ($)', type: 'number', defaultValue: 35000 }
    ],
    formula: 'Inventory Turnover = COGS / Average Inventory\nDays Sales Outstanding (DSO) = (Receivables / Sales Revenue) * 365',
    explanation: 'Assess how quickly inventory is sold and cash from outstanding client invoices is registered in bank accounts.',
    example: 'With $280,000 COGS and $40,000 inventory, inventory turns over 7.0 times per year. $35,000 receivables yields a collection time (DSO) of 25.6 days.',
    faq: [
      { question: 'What is a good inventory turnover ratio?', answer: 'Ratios between 4 and 10 are ideal for most businesses, indicating strong demand without risk of stockouts.' },
      { question: 'What does DSO represent?', answer: 'Days Sales Outstanding represents the average days it takes your team to collect customer invoices. Lower values improve your cash-flow liquidity.' }
    ],
    relatedSlugs: ['employee-productivity-calculator', 'inventory-profit-calculator'],
    calculate: (inputs) => {
      const sales = Number(inputs.salesRevenue || 500000);
      const cogsVal = Number(inputs.cogs || 280000);
      const inv = Number(inputs.averageInventory || 40000);
      const rec = Number(inputs.receivables || 35000);

      const invTurnover = inv > 0 ? cogsVal / inv : 0;
      const dso = sales > 0 ? (rec / sales) * 365 : 0;
      const capitalCycleDays = invTurnover > 0 ? (365 / invTurnover) + dso : 0;

      return {
        results: [
          { label: 'Inventory Turnover Ratio', value: `${invTurnover.toFixed(2)}x`, isPrimary: true },
          { label: 'Days Sales Outstanding (DSO)', value: `${dso.toFixed(1)} Days` },
          { label: 'Cash Conversion Cycle Days', value: `${capitalCycleDays.toFixed(1)} Days` },
          { label: 'Inventory Days on Hand', value: `${invTurnover > 0 ? (365 / invTurnover).toFixed(1) : '0'} Days` }
        ],
        chartData: [
          { name: 'Average Inventory Valuation ($)', value: inv },
          { name: 'Outstanding Receivables ($)', value: rec }
        ]
      };
    }
  },
  {
    id: 'inventory-profit',
    name: 'Inventory Profit Calculator',
    slug: 'inventory-profit-calculator',
    category: 'business',
    description: 'Determine total gross profit yields and margin percentages on inventory batches based on volume and markups.',
    seoTitle: 'Inventory Batch Profit & Markup Calculator',
    seoDescription: 'Obtain expected yield estimates for new stock. Calculate markup rates and batch profits with ease.',
    inputs: [
      { id: 'batchSize', label: 'Inventory Units Batch size', type: 'number', defaultValue: 500 },
      { id: 'unitCost', label: 'Unit Cost From Supplier ($)', type: 'number', defaultValue: 18 },
      { id: 'targetMarkup', label: 'Retail Target Markup (%)', type: 'number', defaultValue: 120 }
    ],
    formula: 'Unit Sell Price = Cost * (1 + Markup/100)\nBatch Profit = Batch Size * (Sell Price - Cost)',
    explanation: 'Retail operations rely on high markup multiples to cover physical shipping fees, employee salaries, and storefront overheads.',
    example: 'A 500-unit batch costing $18/unit with 120% markup yields a retail price of $39.60/unit, generating $10,800 in batch profit.',
    faq: [
      { question: 'What is Markup vs Margin?', answer: 'Markup is the percentage added to the wholesale cost to find retail price. Margin is the percentage representing profit relative to retail price. Markup is always higher than margin.' },
      { question: 'How is Retail Price related to Markup?', answer: 'Retail Price = Cost + (Cost * Markup / 100).' }
    ],
    relatedSlugs: ['product-margin-calculator', 'business-efficiency-calculator'],
    calculate: (inputs) => {
      const size = Number(inputs.batchSize || 1);
      const cost = Number(inputs.unitCost || 0);
      const markup = Number(inputs.targetMarkup || 0);

      const price = cost * (1 + markup / 100);
      const profitPerUnit = price - cost;
      const totalBatchCost = size * cost;
      const totalBatchGrossSales = size * price;
      const totalBatchProfit = size * profitPerUnit;
      const margin = price > 0 ? (profitPerUnit / price) * 100 : 0;

      return {
        results: [
          { label: 'Total Batch Profit Yield', value: `$${totalBatchProfit.toFixed(2)}`, isPrimary: true },
          { label: 'Recommended Retail Price', value: `$${price.toFixed(2)}/unit` },
          { label: 'Initial Inventory Cost', value: `$${totalBatchCost.toFixed(2)}` },
          { label: 'Total Sales Retail Value', value: `$${totalBatchGrossSales.toFixed(2)}` },
          { label: 'Achieved Profit Margin %', value: `${margin.toFixed(2)}%` }
        ],
        chartData: [
          { name: 'Supplier Batch Cost', value: totalBatchCost },
          { name: 'Retained Net Revenue', value: totalBatchProfit }
        ]
      };
    }
  },
  {
    id: 'product-margin',
    name: 'Product Margin Calculator',
    slug: 'product-margin-calculator',
    category: 'business',
    description: 'Calculate product profit margin, selling price, and markup percentage based on wholesale manufacturing costs and target margins.',
    seoTitle: 'Product Profit Margin & Pricing Calculator',
    seoDescription: 'Find product margins easily. Input your cost base and target selling price to find your markup margins.',
    inputs: [
      { id: 'cost', label: 'Wholesale Production Cost ($)', type: 'number', defaultValue: 30 },
      { id: 'price', label: 'Intended Retail Price ($)', type: 'number', defaultValue: 75 }
    ],
    formula: 'Profit Margin = ((Price - Cost) / Price) * 100\nMarkup = ((Price - Cost) / Cost) * 100',
    explanation: 'Quickly find pricing layouts. Protect your margins from rising supplier logistics and material costs.',
    example: 'Producing a product for $30 and selling it at $75 yields a 60% profit margin and a 150% retail markup rate.',
    faq: [
      { question: 'What is a healthy average product margin?', answer: 'Healthy margins depend on industry: physical goods typically target 50-60%, whereas digital SaaS products can achieve 80-92% operating margins.' },
      { question: 'Why does margin never cross 100%?', answer: 'Profit margin measures profit divided by selling price. Since price is always higher than profit, margins can never reach or exceed 100%.' }
    ],
    relatedSlugs: ['inventory-profit-calculator', 'sales-target-calculator'],
    calculate: (inputs) => {
      const cost = Number(inputs.cost || 0);
      const price = Number(inputs.price || 1);

      const margin = price > 0 ? ((price - cost) / price) * 100 : 0;
      const profit = Math.max(0, price - cost);
      const markup = cost > 0 ? ((price - cost) / cost) * 100 : 0;

      return {
        results: [
          { label: 'Profit Margin Percentage', value: `${margin.toFixed(2)}%`, isPrimary: true },
          { label: 'Markup Percentage', value: `${markup.toFixed(2)}%` },
          { label: 'Gross Profit value', value: `$${profit.toFixed(2)}` },
          { label: 'Selling Cost Ratio', value: `${((cost / price) * 100).toFixed(1)}%` }
        ],
        chartData: [
          { name: 'Wholesale Cost Base', value: cost },
          { name: 'Profit Margin Retained', value: profit }
        ]
      };
    }
  }
];
